// Command reset generates Reset() methods for structs marked with // generate:reset.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

type fieldInfo struct {
	name      string
	typ       string
	isPointer bool
	isSlice   bool
	isMap     bool
	isStruct  bool
	hasReset  bool
}

func main() {
	root := flag.String("root", ".", "root directory to scan")
	flag.Parse()

	if err := generateResetMethods(*root); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func generateResetMethods(root string) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		if d.Name() == "vendor" || strings.HasPrefix(d.Name(), ".") {
			return filepath.SkipDir
		}
		return processPackage(path)
	})
}

func processPackage(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse dir %s: %w", dir, err)
	}
	for pkgName, pkg := range pkgs {
		if err := generateForPackage(fset, pkgName, pkg.Files, dir); err != nil {
			return err
		}
	}
	return nil
}

func generateForPackage(fset *token.FileSet, pkgName string, files map[string]*ast.File, dir string) error {
	structs := make(map[string]*ast.StructType)
	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			genDecl, ok := n.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				return true
			}
			if genDecl.Doc == nil || !strings.Contains(genDecl.Doc.Text(), "generate:reset") {
				return true
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				structs[typeSpec.Name.Name] = structType
			}
			return true
		})
	}
	if len(structs) == 0 {
		genFilePath := filepath.Join(dir, "reset.gen.go")
		if err := os.Remove(genFilePath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove stale reset.gen.go: %w", err)
		}
		return nil
	}

	existingResets := findExistingResets(files)
	var buf bytes.Buffer
	buf.WriteString("// Code generated by reset generator; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	buf.WriteString("// Reset resets the receiver to its zero state.\n")

	for name, st := range structs {
		if existingResets[name] {
			fmt.Printf("skipping %s.%s: Reset() already defined\n", pkgName, name)
			continue
		}
		method, err := generateResetMethod(name, st, files)
		if err != nil {
			return fmt.Errorf("generate reset for %s.%s: %w", pkgName, name, err)
		}
		buf.WriteString(method)
		buf.WriteString("\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format source: %w", err)
	}
	genFilePath := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(genFilePath, src, 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}
	return nil
}

func findExistingResets(files map[string]*ast.File) map[string]bool {
	resets := make(map[string]bool)
	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			funcDecl, ok := n.(*ast.FuncDecl)
			if !ok || funcDecl.Recv == nil || len(funcDecl.Recv.List) != 1 {
				return true
			}
			recv := funcDecl.Recv.List[0].Type
			var structName string
			switch t := recv.(type) {
			case *ast.StarExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					structName = ident.Name
				}
			case *ast.Ident:
				structName = t.Name
			}
			if structName != "" && funcDecl.Name.Name == "Reset" && funcDecl.Type.Params.NumFields() == 0 {
				resets[structName] = true
			}
			return true
		})
	}
	return resets
}

func generateResetMethod(structName string, st *ast.StructType, files map[string]*ast.File) (string, error) {
	var fields []fieldInfo
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			typ := exprToString(field.Type)
			fields = append(fields, fieldInfo{
				name:      "",
				typ:       typ,
				isPointer: isPointerType(field.Type),
				isStruct:  true,
				hasReset:  typeHasReset(typ, files),
			})
			continue
		}
		for _, name := range field.Names {
			typ := exprToString(field.Type)
			fi := fieldInfo{
				name:      name.Name,
				typ:       typ,
				isPointer: isPointerType(field.Type),
				isSlice:   isSliceType(field.Type),
				isMap:     isMapType(field.Type),
				isStruct:  isStructType(field.Type, files),
			}
			if fi.isStruct || (fi.isPointer && isStructType(derefPointer(field.Type), files)) {
				underlying := typ
				if fi.isPointer {
					underlying = strings.TrimPrefix(typ, "*")
				}
				fi.hasReset = typeHasReset(underlying, files)
			}
			fields = append(fields, fi)
		}
	}

	var body strings.Builder
	body.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", structName))
	body.WriteString("\tif s == nil {\n\t\treturn\n\t}\n")
	for _, f := range fields {
		if f.name == "" {
			if f.hasReset {
				body.WriteString(fmt.Sprintf("\tif resetter, ok := s.%s.(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}\n", f.typ))
			} else if f.isPointer {
				body.WriteString(fmt.Sprintf("\tif s.%s != nil {\n\t\t// embedded pointer field without Reset\n\t}\n", f.typ))
			}
			continue
		}
		switch {
		case f.isSlice:
			body.WriteString(fmt.Sprintf("\ts.%s = s.%s[:0]\n", f.name, f.name))
		case f.isMap:
			body.WriteString(fmt.Sprintf("\tclear(s.%s)\n", f.name))
		case f.isPointer && f.hasReset:
			body.WriteString(fmt.Sprintf("\tif s.%s != nil {\n\t\ts.%s.Reset()\n\t}\n", f.name, f.name))
		case f.isPointer && !f.hasReset && f.isStruct:
			body.WriteString(fmt.Sprintf("\t// pointer to struct without Reset: s.%s unchanged\n", f.name))
		case f.isPointer:
			zero := zeroValueForType(strings.TrimPrefix(f.typ, "*"))
			body.WriteString(fmt.Sprintf("\tif s.%s != nil {\n\t\t*s.%s = %s\n\t}\n", f.name, f.name, zero))
		case f.isStruct && f.hasReset:
			body.WriteString(fmt.Sprintf("\ts.%s.Reset()\n", f.name))
		default:
			zero := zeroValueForType(f.typ)
			body.WriteString(fmt.Sprintf("\ts.%s = %s\n", f.name, zero))
		}
	}
	body.WriteString("}\n")
	return body.String(), nil
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.ArrayType:
		return "[]" + exprToString(t.Elt)
	case *ast.MapType:
		return "map[" + exprToString(t.Key) + "]" + exprToString(t.Value)
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	default:
		return "unknown"
	}
}

func isPointerType(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)
	return ok
}

func isSliceType(expr ast.Expr) bool {
	_, ok := expr.(*ast.ArrayType)
	return ok
}

func isMapType(expr ast.Expr) bool {
	_, ok := expr.(*ast.MapType)
	return ok
}

func isStructType(expr ast.Expr, files map[string]*ast.File) bool {
	// Simplified; we rely on hasReset detection.
	return false
}

func derefPointer(expr ast.Expr) ast.Expr {
	if star, ok := expr.(*ast.StarExpr); ok {
		return star.X
	}
	return expr
}

func typeHasReset(typeName string, files map[string]*ast.File) bool {
	for _, file := range files {
		var found bool
		ast.Inspect(file, func(n ast.Node) bool {
			funcDecl, ok := n.(*ast.FuncDecl)
			if !ok || funcDecl.Recv == nil || len(funcDecl.Recv.List) != 1 {
				return true
			}
			recvType := exprToString(funcDecl.Recv.List[0].Type)
			recvType = strings.TrimPrefix(recvType, "*")
			if recvType == typeName && funcDecl.Name.Name == "Reset" && funcDecl.Type.Params.NumFields() == 0 {
				found = true
				return false
			}
			return true
		})
		if found {
			return true
		}
	}
	return false
}

func zeroValueForType(typ string) string {
	switch typ {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr":
		return "0"
	case "float32", "float64":
		return "0.0"
	case "complex64", "complex128":
		return "0"
	case "bool":
		return "false"
	case "string":
		return `""`
	default:
		return typ + "{}"
	}
}
