// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/metrics/v1/metrics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_MType int32

const (
	Metric_GAUGE   Metric_MType = 0
	Metric_COUNTER Metric_MType = 1
)

// Enum value maps for Metric_MType.
var (
	Metric_MType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	Metric_MType_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x Metric_MType) Enum() *Metric_MType {
	p := new(Metric_MType)
	*p = x
	return p
}

func (x Metric_MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_metrics_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (Metric_MType) Type() protoreflect.EnumType {
	return &file_api_metrics_v1_metrics_proto_enumTypes[0]
}

func (x Metric_MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MType.Descriptor instead.
func (Metric_MType) EnumDescriptor() ([]byte, []int) {
	return file_api_metrics_v1_metrics_proto_rawDescGZIP(), []int{0, 0}
}

// Metric – единичная метрика
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Metric_MType           `protobuf:"varint,2,opt,name=type,proto3,enum=metrics.v1.Metric_MType" json:"type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_metrics_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() Metric_MType {
	if x != nil {
		return x.Type
	}
	return Metric_GAUGE
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Запрос на обновление метрик (батч)
type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_api_metrics_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Пустой ответ
type UpdateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_api_metrics_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_metrics_proto_rawDescGZIP(), []int{2}
}

var File_api_metrics_v1_metrics_proto protoreflect.FileDescriptor

const file_api_metrics_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1capi/metrics/v1/metrics.proto\x12\n" +
	"metrics.v1\"\x93\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.metrics.v1.Metric.MTypeR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"\x1f\n" +
	"\x05MType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\"D\n" +
	"\x14UpdateMetricsRequest\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.metrics.v1.MetricR\ametrics\"\x17\n" +
	"\x15UpdateMetricsResponse2_\n" +
	"\aMetrics\x12T\n" +
	"\rUpdateMetrics\x12 .metrics.v1.UpdateMetricsRequest\x1a!.metrics.v1.UpdateMetricsResponseB0Z.github.com/eugegm01-dev/metrics/api/metrics/v1b\x06proto3"

var (
	file_api_metrics_v1_metrics_proto_rawDescOnce sync.Once
	file_api_metrics_v1_metrics_proto_rawDescData []byte
)

func file_api_metrics_v1_metrics_proto_rawDescGZIP() []byte {
	file_api_metrics_v1_metrics_proto_rawDescOnce.Do(func() {
		file_api_metrics_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metrics_v1_metrics_proto_rawDesc), len(file_api_metrics_v1_metrics_proto_rawDesc)))
	})
	return file_api_metrics_v1_metrics_proto_rawDescData
}

var file_api_metrics_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_metrics_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_metrics_v1_metrics_proto_goTypes = []any{
	(Metric_MType)(0),             // 0: metrics.v1.Metric.MType
	(*Metric)(nil),                // 1: metrics.v1.Metric
	(*UpdateMetricsRequest)(nil),  // 2: metrics.v1.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil), // 3: metrics.v1.UpdateMetricsResponse
}
var file_api_metrics_v1_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.v1.Metric.type:type_name -> metrics.v1.Metric.MType
	1, // 1: metrics.v1.UpdateMetricsRequest.metrics:type_name -> metrics.v1.Metric
	2, // 2: metrics.v1.Metrics.UpdateMetrics:input_type -> metrics.v1.UpdateMetricsRequest
	3, // 3: metrics.v1.Metrics.UpdateMetrics:output_type -> metrics.v1.UpdateMetricsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_metrics_v1_metrics_proto_init() }
func file_api_metrics_v1_metrics_proto_init() {
	if File_api_metrics_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metrics_v1_metrics_proto_rawDesc), len(file_api_metrics_v1_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metrics_v1_metrics_proto_goTypes,
		DependencyIndexes: file_api_metrics_v1_metrics_proto_depIdxs,
		EnumInfos:         file_api_metrics_v1_metrics_proto_enumTypes,
		MessageInfos:      file_api_metrics_v1_metrics_proto_msgTypes,
	}.Build()
	File_api_metrics_v1_metrics_proto = out.File
	file_api_metrics_v1_metrics_proto_goTypes = nil
	file_api_metrics_v1_metrics_proto_depIdxs = nil
}
